name: Rust

on:
  push:
    paths:
    - 'build.rs'
    - 'src/**'
    - 'examples/**'
    - '.github/workflows/main.yml'
  pull_request:
    paths:
    - 'build.rs'
    - 'src/**'
    - 'examples/**'
    - '.github/workflows/main.yml'

jobs:
  build:
    env:
      CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
        with:
            submodules: recursive

      - name: Install stable rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: prepare-linux
        if: runner.os == 'Linux'
        run: |
            sudo apt-get update
            sudo apt-get install libglu1-mesa-dev mesa-common-dev xorg-dev libasound-dev

      - name: Run cargo build --all-targets
        run: cargo build

      - name: Run cargo build for imgui example
        working-directory: ./examples/imgui
        run: cargo build
